targets:
  $default:
    builders:
      json_serializable:
        enabled: true
        generate_for:
          exclude:
            - test
          include:
            - lib/feature/**/*.dart
      freezed:
        enabled: true
        generate_for:
          exclude:
            - test
          include:
            - lib/feature/**/*.dart

builders:
  json_serializable:
    import: "package:json_serializable/builder.dart"
    builder_factories: ["jsonSerializable"]
    build_extensions: {".dart": ["json_serializable.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
  freezed:
    import: "package:freezed/builder.dart"
    builder_factories: ["freezed"]
    build_extensions: { ".dart": [".freezed.dart"] }
    auto_apply: dependents
    build_to: source
    runs_before: ["json_serializable|json_serializable"]